/*
 * This file is generated by jOOQ.
 */
package eu.dissco.dataexporter.database.jooq;


import eu.dissco.dataexporter.database.jooq.tables.ExportQueue;
import eu.dissco.dataexporter.database.jooq.tables.records.ExportQueueRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExportQueueRecord> EXPORT_QUEUE_PK = Internal.createUniqueKey(ExportQueue.EXPORT_QUEUE, DSL.name("export_queue_pk"), new TableField[] { ExportQueue.EXPORT_QUEUE.ID }, true);
}
