/*
 * This file is generated by jOOQ.
 */
package eu.dissco.dataexporter.database.jooq;


import eu.dissco.dataexporter.database.jooq.tables.ExportQueue;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.export_queue</code>.
     */
    public final ExportQueue EXPORT_QUEUE = ExportQueue.EXPORT_QUEUE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ExportQueue.EXPORT_QUEUE
        );
    }
}
