/*
 * This file is generated by jOOQ.
 */
package eu.dissco.dataexporter.database.jooq;


import eu.dissco.dataexporter.database.jooq.tables.ExportQueue;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.export_queue</code>.
     */
    public static final ExportQueue EXPORT_QUEUE = ExportQueue.EXPORT_QUEUE;
}
