/*
 * This file is generated by jOOQ.
 */
package eu.dissco.dataexporter.database.jooq.tables.records;


import eu.dissco.dataexporter.database.jooq.enums.ExportType;
import eu.dissco.dataexporter.database.jooq.tables.ExportQueue;

import java.time.LocalDate;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExportQueueRecord extends TableRecordImpl<ExportQueueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.export_queue.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.export_queue.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.export_queue.params</code>.
     */
    public void setParams(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.export_queue.params</code>.
     */
    public JSONB getParams() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.export_queue.creator</code>.
     */
    public void setCreator(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.export_queue.creator</code>.
     */
    public String getCreator() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.export_queue.job_state</code>.
     */
    public void setJobState(Object value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.export_queue.job_state</code>.
     */
    public Object getJobState() {
        return get(3);
    }

    /**
     * Setter for <code>public.export_queue.time_scheduled</code>.
     */
    public void setTimeScheduled(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.export_queue.time_scheduled</code>.
     */
    public LocalDate getTimeScheduled() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.export_queue.time_started</code>.
     */
    public void setTimeStarted(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.export_queue.time_started</code>.
     */
    public LocalDate getTimeStarted() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.export_queue.time_completed</code>.
     */
    public void setTimeCompleted(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.export_queue.time_completed</code>.
     */
    public LocalDate getTimeCompleted() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.export_queue.export_type</code>.
     */
    public void setExportType(ExportType value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.export_queue.export_type</code>.
     */
    public ExportType getExportType() {
        return (ExportType) get(7);
    }

    /**
     * Setter for <code>public.export_queue.hashed_params</code>.
     */
    public void setHashedParams(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.export_queue.hashed_params</code>.
     */
    public UUID getHashedParams() {
        return (UUID) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExportQueueRecord
     */
    public ExportQueueRecord() {
        super(ExportQueue.EXPORT_QUEUE);
    }

    /**
     * Create a detached, initialised ExportQueueRecord
     */
    public ExportQueueRecord(UUID id, JSONB params, String creator, Object jobState, LocalDate timeScheduled, LocalDate timeStarted, LocalDate timeCompleted, ExportType exportType, UUID hashedParams) {
        super(ExportQueue.EXPORT_QUEUE);

        setId(id);
        setParams(params);
        setCreator(creator);
        setJobState(jobState);
        setTimeScheduled(timeScheduled);
        setTimeStarted(timeStarted);
        setTimeCompleted(timeCompleted);
        setExportType(exportType);
        setHashedParams(hashedParams);
        resetChangedOnNotNull();
    }
}
